Updated release guide with support details
CoreWCF/CoreWCF pull request #600
Opened 2022-04-12 17:40 UTC by samsp-msft

2022-04-15 14:57 UTC, mjrousos requested changes
This looks good but I think we need some more detail about how long major versions of CoreWCF will be supported.

2022-04-15 14:57 UTC, mjrousos commented on Documentation/release-guide.md
> +- Minor versions will be supported for 6 months after the successor ships.
We're missing verbiage on how long major versions will be supported. After 3.0 is released, how long will we support 2.x? I think that should be called out more clearly here.

2022-04-15 20:16 UTC, mconnew commented
/azp run

2022-04-28 07:50 UTC, mconnew approved these changes

2022-04-28 07:52 UTC, merged